
<?php if(!isset($_SESSION)){
    session_start();
}?>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>


    <!--FontAwesome-->
  <link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"
  integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ="
  crossorigin="anonymous"
/>  
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    

</head>

<body>


    
    <nav class="navbar">
    <button  style="outline:0" class="toggle" id="toggle">
      <i class="fas fa-bars fa-3x" style="color:yellow;"  ></i>
    </button>
 
        <div class="navbar-logo">
            <img src="../assets/images/projectImages/logo.png" alt="logo" class="navImg">
            <h1>The Garage </h1>
        </div>
        <ul id="navlist">
       
           <a href="index.php">

           <li class="hover" id="homelink">Home</li>
          </a> 
          <a href="search.php?allcars=yes">
            <li class="hover" id="carslink" href=>Cars</li>
            </a>
  
            <a href="contact.php">
            <li class="hover" id="contactlink"> Contact </li></a>
            
         <?php
         //print_r( $_SESSION); 
         if(isset($_SESSION['userLoggedIn'])){
echo "<span class='signedin'>
          <a >
            <i class='fas fa-user fa-2x' style='float:left'></i>
              <h2 style='float:right; margin-left:10px;'>  ". $_SESSION['userLoggedIn']. "</h2>
              </a>
       </span>";

         }
           else echo" <li class='loginnavbutton'> <a href='signin.php'>LogIn</a></li>
            <li class='registernavbutton'>
                <a href='register.php'>Register</a> </li>";
                
                ?>

        </ul>

    </nav>
    <!-- end navbar-->


    <nav class="navlogo">
    <!-- logo area (generated by random just out a number)-->

    <?php

    if(isset($_SESSION['userLoggedIn'])){
      echo "<div class='logo'>
    <img src='https://img.icons8.com/external-kiranshastry-gradient-kiranshastry/64/000000/external-user-interface-kiranshastry-gradient-kiranshastry.png' > <h1 style='color:darkblue'> ".$_SESSION['userLoggedIn']. "</h1>
  </div>";
    }
    ?>
    
    <ul>

    <?php

if(!isset($_SESSION['userLoggedIn'])){
  echo "<div class='logo' >
  <img  style='margin-top:20px'src='https://icon-library.com/images/guest-account-icon/guest-account-icon-1.jpg'>
</div>
<li><a href='signin.php'>Sign In  </a></li>
  <li><a href='register.php'>Create An Account  </a></li>";
}
?>

      <li ><a href="index.php" >HOME </a></li>
      <li ><a href="search.php?allcars=yes" >Cars </a></li>
      <li ><a href="contact.php" >Contact Us </a></li>
      
    </ul>
  </nav><!--end navlogo nav  bar-->
  
  

</body>

<script>


const toggle=document.querySelector("#toggle");


toggle.addEventListener("click",()=>{
  /*toggle change the state to the opposite*/
  document.body.classList.toggle("show-nav")
  if(document.body.classList.contains('show-nav'))
         //console.log(document.querySelector('#navlist').style.marginRight="40px";)
         document.querySelector('#navlist').style.marginRight="210px";
    else
    document.querySelector('#navlist').style.marginRight="20px";
  
})



</script>
